services:
  # 1. PostgreSQL DB 컨테이너 추가
  helios-db:
    image: postgres:15-alpine
    container_name: helios-db
    environment:
      - POSTGRES_DB=helios_db      
      - POSTGRES_USER=helios_user  
      - POSTGRES_PASSWORD=helios4    
    ports:
      - "5432:5432"
    networks:
      - helios-network

  # 2. 백엔드
  helios-backend:
    build: ./helios_backend
    container_name: helios-backend
    depends_on:
      - helios-db # DB가 먼저 시작되도록 설정
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://helios-db:5432/helios_db
      - SPRING_DATASOURCE_USERNAME=helios_user
      - SPRING_DATASOURCE_PASSWORD=helios4
      - AI_SERVER_URL=http://helios-ai:8000
    ports:
      - "8081:8081"
    networks:
      - helios-network

  # 프론트엔드
  helios-client:
    build: ./Heliosclient
    container_name: helios-client
    ports:
      - "3000:80"
    networks:
      - helios-network

  # AI 서버
  helios-ai:
    build: ./helios_ai 
    container_name: helios-ai
    environment:
      - SPRING_BOOT_URL=http://helios-backend:8081
    ports:
      - "8083:8083"    # 웹소켓이나 다른 통신용
      - "8080:8000"    # 백엔드와 통신용
    networks:
      - helios-network
    restart: always    # 오류 시 자동 재시작

networks:
  helios-network:
    driver: bridge